version: '2'

services:

  databases:
    image: postgres:9.6
    container_name: mydb
    ports:
      - "5432:5432"
    #  - "${DOCKER_PORTGRES_PORT}:5432"
    #volumes:
    #  - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      main:
        aliases:
          - databases

  container:
    image: tomcat:8.5.35-jre8
    container_name: mytomcat8
    environment:
    - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
    depends_on:
      - databases
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      main:
        aliases:
          - pfm

networks:
    main: